### DISCUSSION TITLE
support attributes for toml

### DISCUSSION THREAD

**Discussion by cooperspencer** [vlang/v#18581] [Ideas]
# V Doctor:
```bash
OS: linux, Pop!_OS 22.04 LTS
Processor: 8 cpus, 64bit, little endian, 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
CC version: cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0

getwd: /home/andreas.wachter/git/vackup
vmodules: /home/andreas.wachter/.vmodules
vroot: /home/andreas.wachter/git/v
vexe: /home/andreas.wachter/git/v/v
vexe mtime: 2022-07-25 05:31:26
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 f9385f6.7bf2ad6

Git version: git version 2.34.1
Git vroot status: weekly.2022.29-60-g7bf2ad68 (11 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 827f7452
```
# What did you do?
conf.toml
```toml
[backup]
locations = ["~/Documents", "/etc/hosts"]
backupdir = "backup"
keep = 7

[post_backup]
commands = ["echo $BLA", "echo $BACKUP_FILE", "cp $BACKUP_FILE bla.zip"]

[environment_variables]
BLA = "Blub"
```
```v
module main

import os
import toml

struct Conf {
mut:
	post_backup           Post_Backup       [toml: 'post_backup']
	environment_variables map[string]string
	backup                Backup            [toml: 'backup']
}

struct Backup {
	locations []string
mut:
	backupdir string
	keep      i64
}

struct Post_Backup {
	commands []string
}

fn main() {
       conf_file := 'conf.toml'
	doc := toml.parse_file(conf_file) or { panic(err) }

	mut conf := doc.reflect<Conf>()
        print(conf)
}
```

# What did you expect to see?
```
Conf{
    post_backup: Post_Backup{
        commands: ['echo $BLA', 'echo $BACKUP_FILE', 'cp $BACKUP_FILE bla.zip']
    }
    environment_variables: {'BLA': 'Blub'}
    backup: Backup{
        locations: ['~/Documents', '/etc/hosts']
        backupdir: 'backup'
        keep: 7
    }
}
```
# What did you see instead?
```
Conf{
    post_backup: Post_Backup{
        commands: []
    }
    environment_variables: {'BLA': 'Blub'}
    backup: Backup{
        locations: []
        backupdir: ''
        keep: 0
    }
}
```
