### ISSUE TITLE
Maybe use the new Github Action ?

### ISSUE THREAD

**Issue by shiipou** [vlang/v#1931]
Why did you not use the new Github Action that provide full CI/CD for free ?

That very simple to use and very powerful to automaticaly build V, run test, and check so many things like code quality rules for every push or pull_request.
That can filter, sort, and rearange issues automatically, find duplicates etc...

Check it how it work here : 
[https://help.github.com/en/articles/workflow-syntax-for-github-actions](https://help.github.com/en/articles/workflow-syntax-for-github-actions)

**Comment by spytheman** [comment]
First time heard about that github feature...

From the page you linked:
>> GitHub Actions is currently in limited public beta and is subject to change. We strongly recommend that you do not use this feature for high-value workflows and content during the beta period.

Have you used this functionality yourself, are you satisfied?

**Comment by medvednikov** [comment]
Will check it out, thanks.

YAML again...

**Comment by shiipou** [comment]
Yes I use it for my new project, And it's faster than gitlab-ci (on gitlab) or fire-ci (on github).
It's for me, easier to configure than those two.

For exemple you can use this yaml file to build v binary : 
```yaml
name: Build binary
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from Git repository
      uses: actions/checkout@v1 # You can use v1 or master but v1 is recommanded
    - name: Build
      run: make && sudo ./v symlink
    - name: test
      run: v test ./tests_directory/
   - name: Publish
      uses: toolmantim/release-drafter@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

You can define custom action that you can use into your yaml build script with : 
```yaml
   - name: My first step
     uses: ./.github/actions/my-action
```

**Comment by medvednikov** [comment]
Sounds nice @shiipou 

The builds are my favorite part.

I've applied, hopefully won't take too long ;)

**Comment by shiipou** [comment]
@medvednikov I've got added to the beta in two days
Yes, the build is so simple, no deps to install, so many things already installed on the base ubuntu image that github Action use.

**Comment by medvednikov** [comment]
I just got accepted @shiipou 

Will try to set it up now

**Comment by shiipou** [comment]
@medvednikov

Check my fork, I've setup basic one :
Nocturlab/v

**Comment by medvednikov** [comment]
Thanks!

**Comment by medvednikov** [comment]
@shiipou looks like it's not possible to create a github release

**Comment by shiipou** [comment]
Look at here :
https://github.com/toolmantim/release-drafter

**Comment by shiipou** [comment]
This use the github API to create the draft release.

**Comment by medvednikov** [comment]
Yes, of course it's possible to use an external tool (preferably not written in JavaScript), that's what I already do, but I was hoping it'd be supported natively.

**Comment by shiipou** [comment]
Github didn't really support it directly.

But the github repository I send you can be called by the github action directly :

```yaml
   - name: Create Release
      uses: toolmantim/release-drafter@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
Github work in that way, a sort of plugin you can use in steps.
