### ISSUE TITLE
Initializing fixed array with optional results in error

### ISSUE THREAD

**Issue by lv37** [vlang/v#19385]
### Describe the bug

see title

### Reproduction Steps

```v
module main

fn main() {
	_ := [10]?int{} // error: expression evaluated but not used
}
```

### Expected Behavior

compile

### Current Behavior

```v
main.v:4:12: error: expression evaluated but not used
    2 | 
    3 | fn main() {
    4 |     _ := [10]?int{}
      |               ~~~~~
    5 | }
```

### V version

V 0.4.1 fdabd27

### Environment details (OS name and version, etc.)

```yaml
V full version: V 0.4.1 52a055b.fdabd27
OS: linux, Linux version 6.4.12-200.fc38.x86_64 (mockbuild@30894952d3244f1ab967aeda9ed417f6) (gcc (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1), GNU ld version 2.39-9.fc38) #1 SMP PREEMPT_DYNAMIC Wed Aug 23 17:46:49 UTC 2023
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz

getwd: /home/user/Projects/v-testing/mineflayer
vexe: /home/user/.local/lib/v/v
vexe mtime: 2023-09-19 11:41:13

vroot: OK, value: /home/user/.local/lib/v
VMODULES: OK, value: /home/user/.vmodules
VTMP: OK, value: /tmp/v_1002

Git version: git version 2.41.0
Git vroot status: 0.4.1-100-gfdabd27b
.git/config present: true

CC version: cc (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```
> [!IMPORTANT]
> You can vote for this issue using the 👍 reaction. More votes increase the issue's priority
> for developers.
>
> Take into account that only the 👍 reaction counts as a vote.
> Only reactions to the issue itself will be counted as votes, not comments.
