### ISSUE TITLE
C error when importing local submodule without `v.mod` file

### ISSUE THREAD

**Issue by lv37** [vlang/v#19782]
### Describe the bug

Trying to compile
```v
module main

import abc.def

fn main() {}
```
gives
```
/tmp/v_1002/main.15167110308330651613.tmp.c:672: error: ';' expected (got "MessageError")
```

### Reproduction Steps

```
.
└── src
    ├── abc
    │   └── def
    │       └── def.v
    └── main.v
```

`main.v`
```v
module main

import abc.def

fn main() {}
```

`def.v`
```v
module def
```
compile with `v ./src`

### Expected Behavior

compile

### Current Behavior

```
/tmp/v_1002/main.15167110308330651613.tmp.c:672: error: ';' expected (got "MessageError")
```

### V version

V 0.4.2 140c838

### Environment details (OS name and version, etc.)

```yaml
V full version: V 0.4.2 4bc9a8f.140c838
OS: linux, Linux version 6.5.9-200.fc38.x86_64 (mockbuild@1cc7d6d790524511abd343182a21832a) (gcc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4), GNU ld version 2.39-15.fc38) #1 SMP PREEMPT_DYNAMIC Wed Oct 25 20:40:49 UTC 2023
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz

getwd: /home/user/Projects/v-testing/webview
vexe: /home/user/.local/lib/v/v
vexe mtime: 2023-11-06 10:34:17

vroot: OK, value: /home/user/.local/lib/v
VMODULES: OK, value: /home/user/.vmodules
VTMP: OK, value: /tmp/v_1002

Git version: git version 2.41.0
Git vroot status: weekly.2023.44-63-g140c838f
.git/config present: true

CC version: cc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4)
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.
