### ISSUE TITLE
Cannot pass fixed array as generic

### ISSUE THREAD

**Issue by wygsh** [vlang/v#19863]
### Describe the bug

```v
module main

fn generic[T]() {}

fn main() {
	generic[[3]int]()
}
```

gives multiple errors
```
src/main.v:6:10: warning: use e.g. `x := [1]Type{}` instead of `x := [1]Type`
src/main.v:6:9: error: type `generic` does not support indexing
src/main.v:6:18: error: unknown function:
src/main.v:3:1: error: generic function visited more than 10000 times
```

### Reproduction Steps

try to compile the above code

### Expected Behavior

compile successfully

### Current Behavior

```v
src/main.v:6:10: warning: use e.g. `x := [1]Type{}` instead of `x := [1]Type`
    4 | 
    5 | fn main() {
    6 |     generic[[3]int]()
      |             ~~~~~~~
    7 | }
src/main.v:6:9: error: type `generic` does not support indexing
    4 | 
    5 | fn main() {
    6 |     generic[[3]int]()
      |            ~~~~~~~~
    7 | }
src/main.v:6:18: error: unknown function: 
    4 | 
    5 | fn main() {
    6 |     generic[[3]int]()
      |                     ^
    7 | }
src/main.v:3:1: error: generic function visited more than 10000 times
    1 | module main
    2 | 
    3 | fn generic[T]() {}
      | ~~~~~~~~~~~~~~~
    4 | 
    5 | fn main() {
```

### V version

V 0.4.3 55cac88

### Environment details (OS name and version, etc.)

```yaml
V full version: V 0.4.3 4bc9a8f.55cac88
OS: linux, Linux version 6.5.11-300.fc39.x86_64 (mockbuild@d23353abed4340e492bce6e111e27898) (gcc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4), GNU ld version 2.40-13.fc39) #1 SMP PREEMPT_DYNAMIC Wed Nov  8 22:37:57 UTC 2023
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz

getwd: /home/user/Projects/v-testing/embed_dir
vexe: /home/user/.local/lib/v/v
vexe mtime: 2023-11-13 18:36:34

vroot: OK, value: /home/user/.local/lib/v
VMODULES: OK, value: /home/user/.vmodules
VTMP: OK, value: /tmp/v_1002

Git version: git version 2.41.0
Git vroot status: weekly.2023.45.1-21-g55cac884
.git/config present: true

CC version: cc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4)
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.
