### ISSUE TITLE
C error when trying to initialize generic fixed array type

### ISSUE THREAD

**Issue by wygsh** [vlang/v#19872]
### Describe the bug

Trying to compile
```v
module main

fn init_type[T]() T {
	return T{}
}

fn main() {
	init_type[[3]int]()
}
```
gives
```
/tmp/v_1002/src.170089672244163027.tmp.c:12624: error: '{' expected (got ";")
```

### Reproduction Steps

Try to compile the above code

### Expected Behavior

Compile successfully

### Current Behavior

```
/tmp/v_1002/src.170089672244163027.tmp.c:12624: error: '{' expected (got ";")
```

### V version

V 0.4.3 4628fe7

### Environment details (OS name and version, etc.)

```yaml
V full version: V 0.4.3 4bc9a8f.4628fe7
OS: linux, Linux version 6.5.11-300.fc39.x86_64 (mockbuild@d23353abed4340e492bce6e111e27898) (gcc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4), GNU ld version 2.40-13.fc39) #1 SMP PREEMPT_DYNAMIC Wed Nov  8 22:37:57 UTC 2023
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz

getwd: /home/user/Projects/v-testing/embed_dir
vexe: /home/user/.local/lib/v/v
vexe mtime: 2023-11-14 10:16:10

vroot: OK, value: /home/user/.local/lib/v
VMODULES: OK, value: /home/user/.vmodules
VTMP: OK, value: /tmp/v_1002

Git version: git version 2.41.0
Git vroot status: weekly.2023.45.1-25-g4628fe76
.git/config present: true

CC version: cc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4)
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.
