### ISSUE TITLE
Cannot pass struct field to generic method

### ISSUE THREAD

**Issue by lv37** [vlang/v#20026]
### Describe the bug

Trying to compile:
```v
module main

struct Struct {
	a int
	b string
}

struct Abc{}

fn (a Abc) generic[T](b T) {
	$if T is $struct {
		$for f in T.fields {
			a.generic(b.$(f.name))
		}
	}
}

fn main() {
	Abc{}.generic(Struct{})
}
```
gives:
```v
src/main.v:13:14: error: cannot use `string` as `int` in argument 1 to `Abc.generic`
   11 |     $if T is $struct {
   12 |         $for f in T.fields {
   13 |             a.generic(b.$(f.name))
      |                       ~~~~~~~~~~~
   14 |         }
   15 |     }
```

### Reproduction Steps

Try to compile the above code

### Expected Behavior

Compile successfully

### Current Behavior

```v
src/main.v:13:14: error: cannot use `string` as `int` in argument 1 to `Abc.generic`
   11 |     $if T is $struct {
   12 |         $for f in T.fields {
   13 |             a.generic(b.$(f.name))
      |                       ~~~~~~~~~~~
   14 |         }
   15 |     }
```

### V version

V 0.4.3 782bf86

### Environment details (OS name and version, etc.)

```yaml
V full version: V 0.4.3 b347f54.782bf86
OS: linux, Linux version 6.5.12-300.fc39.x86_64 (mockbuild@cda4963b6857459f9d1b40ea59f8a44a) (gcc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4), GNU ld version 2.40-13.fc39) #1 SMP PREEMPT_DYNAMIC Mon Nov 20 22:44:24 UTC 2023
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz

getwd: /home/user/Projects/v-testing/neofetch-clone
vexe: /home/user/.local/lib/v/v
vexe mtime: 2023-11-28 14:50:01

vroot: OK, value: /home/user/.local/lib/v
VMODULES: OK, value: /home/user/.vmodules
VTMP: OK, value: /tmp/v_1002

Git version: git version 2.43.0
Git vroot status: weekly.2023.48-8-g782bf865
.git/config present: true

CC version: cc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4)
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.
