### ISSUE TITLE
 Invalid memory access when changing map value in generic function

### ISSUE THREAD

**Issue by wygsh** [vlang/v#20037]
### Describe the bug

Trying to run
```v
module main

fn merged[K, V](a map[K]V, b map[K]V) map[K]V {
	mut o := a.clone()
	for k, v in b {
		$if V is $map {
			o[k] = merged(o[k], v)
		} $else {
			o[k] = v
		}
	}
	return o
}

fn main() {
	a := { 'aa': { '11': 1 } }
	b := { 'bb': { '22': 2 } }
	c := merged(a, b)
	println(c) // should print {'aa': {'11': 1}, 'bb': {'22': 2}}
}
```
gives the following error
```
7f4298476840 : at ???: RUNTIME ERROR: invalid memory access
/tmp/v_1002/test.tmp.c:9011: by map_clone
/tmp/v_1002/test.tmp.c:12677: by main__merged_T_string_Map_string_int
/tmp/v_1002/test.tmp.c:12692: by main__merged_T_string_Map_string_int
/tmp/v_1002/test.tmp.c:12692: by main__merged_T_string_Map_string_int
/tmp/v_1002/test.tmp.c:12763: by main__main
/tmp/v_1002/test.tmp.c:12800: by main
```

### Reproduction Steps

Trying to run the above code

### Expected Behavior

print `{'aa': {'11': 1}, 'bb': {'22': 2}}` then exit

### Current Behavior

```
7f4298476840 : at ???: RUNTIME ERROR: invalid memory access
/tmp/v_1002/test.tmp.c:9011: by map_clone
/tmp/v_1002/test.tmp.c:12677: by main__merged_T_string_Map_string_int
/tmp/v_1002/test.tmp.c:12692: by main__merged_T_string_Map_string_int
/tmp/v_1002/test.tmp.c:12692: by main__merged_T_string_Map_string_int
/tmp/v_1002/test.tmp.c:12763: by main__main
/tmp/v_1002/test.tmp.c:12800: by main
```

### V version

V 0.4.3 782bf86

### Environment details (OS name and version, etc.)

```yaml
V full version: V 0.4.3 b347f54.782bf86
OS: linux, Linux version 6.5.12-300.fc39.x86_64 (mockbuild@cda4963b6857459f9d1b40ea59f8a44a) (gcc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4), GNU ld version 2.40-13.fc39) #1 SMP PREEMPT_DYNAMIC Mon Nov 20 22:44:24 UTC 2023
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz

getwd: /home/user/Projects/v-testing/webview/utils
vexe: /home/user/.local/lib/v/v
vexe mtime: 2023-11-28 14:50:01

vroot: OK, value: /home/user/.local/lib/v
VMODULES: OK, value: /home/user/.vmodules
VTMP: OK, value: /tmp/v_1002

Git version: git version 2.43.0
Git vroot status: weekly.2023.48-8-g782bf865 (1 commit(s) behind V master)
.git/config present: true

CC version: cc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4)
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.
