### ISSUE TITLE
Wrong cast when passing a map to a generic function

### ISSUE THREAD

**Issue by lv37** [vlang/v#20089]
### Describe the bug

```v
module main

fn generic[A](a A) {
	expect_map(A(a))
}

fn expect_map[K, V](a map[K]V) {
	println(a)
}

fn main() {
	a := { 'a': 1 }
	b := { 1: 'a' }
	generic(a) // prints { &int(&'a'): &string(&1) }
	generic(b) // commenting this line makes the one above work as expected
}
```

### Reproduction Steps

Run the above code

### Expected Behavior

It should print:
```
{ 'a': 1 }
{ 1: 'a' }
```

### Current Behavior

It prints:
```
{1757855728: ''}
{1: 'a'}
```

### V version

V 0.4.3 c7b7d5f

### Environment details (OS name and version, etc.)

```yaml
V full version: V 0.4.3 b347f54.c7b7d5f
OS: linux, Linux version 6.5.12-300.fc39.x86_64 (mockbuild@cda4963b6857459f9d1b40ea59f8a44a) (gcc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4), GNU ld version 2.40-13.fc39) #1 SMP PREEMPT_DYNAMIC Mon Nov 20 22:44:24 UTC 2023
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz

getwd: /home/user/Projects/v-testing/hypixel
vexe: /home/user/.local/lib/v/v
vexe mtime: 2023-12-04 16:35:57

vroot: OK, value: /home/user/.local/lib/v
VMODULES: OK, value: /home/user/.vmodules
VTMP: OK, value: /tmp/v_1002

Git version: git version 2.43.0
Git vroot status: weekly.2023.48-48-gc7b7d5f5
.git/config present: true

CC version: cc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4)
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.
