### ISSUE TITLE
Mutable variable in closure not updating in anonymous function

### ISSUE THREAD

**Issue by lv37** [vlang/v#20102]
### Describe the bug

```v
module main

fn main() {
	mut a := 1
	modify_a := fn [mut a] () {
		a = 2 // warning: unused variable: `a` ??
	}
	modify_a()
	println(a) // It should print `2` but it prints `1`
}
```

### Reproduction Steps

Run the above

### Expected Behavior

```
2
```

### Current Behavior

```
src/main.v:5:22: warning: unused variable: `a`
    3 | fn main() {
    4 |     mut a := 1
    5 |     modify_a := fn [mut a] () {
      |                         ^
    6 |         a = 2 // warning: unused variable: `a` ????
    7 |     }
1
```

### V version

V 0.4.3 09d05bb

### Environment details (OS name and version, etc.)

```yaml
V full version: V 0.4.3 b347f54.09d05bb
OS: linux, Linux version 6.6.3-200.fc39.x86_64 (mockbuild@62256c00a5854842b8d1a622060ebc27) (gcc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4), GNU ld version 2.40-13.fc39) #1 SMP PREEMPT_DYNAMIC Tue Nov 28 19:11:52 UTC 2023
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz

getwd: /home/user/Projects/v-testing/hypixel
vexe: /home/user/.local/lib/v/v
vexe mtime: 2023-12-06 09:47:42

vroot: OK, value: /home/user/.local/lib/v
VMODULES: OK, value: /home/user/.vmodules
VTMP: OK, value: /tmp/v_1002

Git version: git version 2.43.0
Git vroot status: weekly.2023.48-59-g09d05bb5
.git/config present: true

CC version: cc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4)
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.
