### ISSUE TITLE
Checker error with interface with generic method

### ISSUE THREAD

**Issue by wygsh** [vlang/v#20430]
### Describe the bug

```v
module main

interface Abc {
	test[T]()
}

struct Xyz {}

fn (xyz Xyz) test[T]() {}

fn main() {
	_ := Abc(Xyz{})
}
```
Gives
```
src/main.v:4:6: error: no need to add generic type names in generic interface's method
```

### Reproduction Steps

Try to compile the above code

### Expected Behavior

Compile successfully

### Current Behavior

```v
src/main.v:4:6: error: no need to add generic type names in generic interface's method
    2 | 
    3 | interface Abc {
    4 |     test[T]()
      |         ^
    5 | }
    6 |
```

### V version

V 0.4.3 66d222c

### Environment details (OS name and version, etc.)

```yaml
V full version: V 0.4.3 b347f54.66d222c
OS: linux, Linux version 6.6.8-200.fc39.x86_64 (mockbuild@f2936e05dca94a129acf79933fec484d) (gcc (GCC) 13.2.1 20231205 (Red Hat 13.2.1-6), GNU ld version 2.40-13.fc39) #1 SMP PREEMPT_DYNAMIC Thu Dec 21 04:01:49 UTC 2023
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz

getwd: /home/user/Projects/v-testing/mineflayer
vexe: /home/user/.local/lib/v/v
vexe mtime: 2024-01-07 13:41:03

vroot: OK, value: /home/user/.local/lib/v
VMODULES: OK, value: /home/user/.vmodules
VTMP: OK, value: /tmp/v_1002

Git version: git version 2.43.0
Git vroot status: weekly.2023.52-96-g66d222cc
.git/config present: true

CC version: cc (GCC) 13.2.1 20231205 (Red Hat 13.2.1-6)
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.
